/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './zone.module';
import * as i2 from './CreateZone/createZone.component.ngfactory';
import * as i3 from './viewZones/viewZones.component.ngfactory';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/http';
import * as i6 from '@angular/common';
import * as i7 from '@agm/core/utils/browser-globals';
import * as i8 from '@agm/core/services/maps-api-loader/maps-api-loader';
import * as i9 from '@agm/core/services/maps-api-loader/lazy-maps-api-loader';
import * as i10 from '@angular/router';
import * as i11 from '@agm/core/core.module';
import * as i12 from './CreateZone/createZone.component';
import * as i13 from './viewZones/viewZones.component';
export const ZonesModuleNgFactory:i0.NgModuleFactory<i1.ZonesModule> = i0.ɵcmf(i1.ZonesModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.CreateZoneComponentNgFactory,i3.ViewZonesComponentNgFactory]],[3,
              i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,
          ([] as any[])),i0.ɵmpd(4608,i5.BrowserXhr,i5.BrowserXhr,([] as any[])),i0.ɵmpd(4608,
          i5.ResponseOptions,i5.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i5.XSRFStrategy,
          i5.ɵb,([] as any[])),i0.ɵmpd(4608,i5.XHRBackend,i5.XHRBackend,[i5.BrowserXhr,
          i5.ResponseOptions,i5.XSRFStrategy]),i0.ɵmpd(4608,i5.RequestOptions,i5.BaseRequestOptions,
          ([] as any[])),i0.ɵmpd(5120,i5.Http,i5.ɵc,[i5.XHRBackend,i5.RequestOptions]),
          i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i7.WindowRef,i7.WindowRef,([] as any[])),i0.ɵmpd(4608,i7.DocumentRef,
              i7.DocumentRef,([] as any[])),i0.ɵmpd(4608,i8.MapsAPILoader,i9.LazyMapsAPILoader,
              [i9.LAZY_MAPS_API_CONFIG,i7.WindowRef,i7.DocumentRef]),i0.ɵmpd(512,i4.ɵba,
              i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.FormsModule,i4.FormsModule,([] as any[])),
          i0.ɵmpd(512,i5.HttpModule,i5.HttpModule,([] as any[])),i0.ɵmpd(512,i6.CommonModule,
              i6.CommonModule,([] as any[])),i0.ɵmpd(512,i10.RouterModule,i10.RouterModule,
              [[2,i10.ɵa],[2,i10.Router]]),i0.ɵmpd(512,i11.AgmCoreModule,i11.AgmCoreModule,
              ([] as any[])),i0.ɵmpd(512,i1.ZonesModule,i1.ZonesModule,([] as any[])),
          i0.ɵmpd(1024,i10.ROUTES,() => {
            return [[{path:'',redirectTo:'createZone'},{path:'createZone',component:i12.CreateZoneComponent},
                {path:'ViewZOnes',component:i13.ViewZonesComponent}]];
          },([] as any[])),i0.ɵmpd(256,i9.LAZY_MAPS_API_CONFIG,{apiKey:'AIzaSyCOSzrV21ii_0a6d8XC08vARjJH2TYbLJs',
              libraries:['places','drawing']},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC96b25lQ3JlYXRpb24vem9uZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC96b25lQ3JlYXRpb24vem9uZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
