/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.instant[_ngcontent-%COMP%]{\r\n    color:#00BFFF\r\n }\r\n .FourHours[_ngcontent-%COMP%]{\r\n    color: #fb641b\r\n }\r\n .same[_ngcontent-%COMP%]{\r\n    color: #ee9b0a\r\n }\r\nh3[_ngcontent-%COMP%]{\r\n    font-weight: 500;\r\n    text-align: center;\r\n    font-size: 23px;\r\n    color: #646464;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9PcmRlcnMvYWxsb3JkZXJzL3BlbmRpbmdvcmRlcnMvcGVuZGluZ29yZGVycy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0V6c2hpcHAvMTMtMDEtMjAxOC9zdXBlcmFkbWluX2FuZ3VsYXIvYXNzZXRzL2FwcC9kYXNoYm9hcmQvT3JkZXJzL2FsbG9yZGVycy9wZW5kaW5nb3JkZXJzL3BlbmRpbmdvcmRlcnMuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
