/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './offers.module';
import * as i2 from '../../../../node_modules/angular2-busy/build/busy.component.ngfactory';
import * as i3 from '../../../../node_modules/angular2-busy/build/busy-backdrop.component.ngfactory';
import * as i4 from '@angular/forms';
import * as i5 from '@angular/common';
import * as i6 from '@angular/http';
import * as i7 from 'ngx-pagination';
import * as i8 from 'angular2-busy/build/busy.service';
import * as i9 from 'angular2-busy/build/busy-config';
import * as i10 from 'angular2-busy/build/busy.module';
import * as i11 from '@angular/router';
import * as i12 from 'ng2-img-cropper/src/imageCropperModule';
import * as i13 from '../../shared/shared.module';
export const OffersModuleNgFactory:i0.NgModuleFactory<i1.OffersModule> = i0.ɵcmf(i1.OffersModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.BusyComponentNgFactory,i3.BusyBackdropComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,
          i5.NgLocalization,i5.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i6.BrowserXhr,
          i6.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i6.ResponseOptions,i6.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(5120,i6.XSRFStrategy,i6.ɵb,([] as any[])),i0.ɵmpd(4608,
          i6.XHRBackend,i6.XHRBackend,[i6.BrowserXhr,i6.ResponseOptions,i6.XSRFStrategy]),
          i0.ɵmpd(4608,i6.RequestOptions,i6.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i6.Http,i6.ɵc,[i6.XHRBackend,i6.RequestOptions]),i0.ɵmpd(4608,i7.PaginationService,
              i7.PaginationService,([] as any[])),i0.ɵmpd(4608,i8.BusyService,i8.BusyService,
              [[2,i9.BusyConfig]]),i0.ɵmpd(5120,i0.Compiler,i10.createJitCompiler,
              ([] as any[])),i0.ɵmpd(512,i11.RouterModule,i11.RouterModule,[[2,i11.ɵa],
              [2,i11.Router]]),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,
              i4.FormsModule,i4.FormsModule,([] as any[])),i0.ɵmpd(512,i5.CommonModule,
              i5.CommonModule,([] as any[])),i0.ɵmpd(512,i12.ImageCropperModule,i12.ImageCropperModule,
              ([] as any[])),i0.ɵmpd(512,i6.HttpModule,i6.HttpModule,([] as any[])),
          i0.ɵmpd(512,i7.NgxPaginationModule,i7.NgxPaginationModule,([] as any[])),
          i0.ɵmpd(512,i13.SharedModule,i13.SharedModule,([] as any[])),i0.ɵmpd(512,
              i10.BusyModule,i10.BusyModule,([] as any[])),i0.ɵmpd(512,i1.OffersModule,
              i1.OffersModule,([] as any[])),i0.ɵmpd(1024,i11.ROUTES,() => {
            return [[{path:'',redirectTo:'create_Offer',pathMatch:'full'},{path:'create_Offer',
                loadChildren:'./sessionalOffer/createoffer.module#CreateOfferModule'},
                {path:'view_offer',loadChildren:'./FirstTimeBooking/FirstTimeBooking.module#ViewallOffersModule'},
                {path:'de_Activate',loadChildren:'./DeactivateOffers/DeactivateOffers.module#DeactivateOffersModule'}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9PZmZlcnMvb2ZmZXJzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9FenNoaXBwLzEzLTAxLTIwMTgvc3VwZXJhZG1pbl9hbmd1bGFyL2Fzc2V0cy9hcHAvZGFzaGJvYXJkL09mZmVycy9vZmZlcnMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
