/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.button-fixed-plus[_ngcontent-%COMP%] {\r\n    position: fixed;\r\n    bottom: 10px;\r\n    right: 10px;\r\n    font-size: 50px;\r\n    \r\n}\r\n\r\n.modal-footer[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n}\r\n\r\n.border-top[_ngcontent-%COMP%] {\r\n    border-top: none;\r\n}\r\n\r\n.table[_ngcontent-%COMP%] {\r\n    margin-bottom: 0px;\r\n  \r\n}\r\n.shadow[_ngcontent-%COMP%]{\r\n    box-shadow: 0 0 4px rgba(0, 0, 0, 0.14), 0 4px 8px rgba(0, 0, 0, 0.28);\r\n    margin-top: 20px;\r\n}\r\n\r\n.close[_ngcontent-%COMP%] {\r\n    font-size: 20px;\r\n}\r\n\r\n.modal-title[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n}\r\n\r\n.form-group[_ngcontent-%COMP%] {\r\n    padding-bottom: 0px;\r\n    margin-top: 0px;\r\n}\r\n.table_date_width[_ngcontent-%COMP%] {\r\n    width: 260px;\r\n}\r\n.date_width[_ngcontent-%COMP%] {\r\n    width: 130px;\r\n}\r\ni.material-icons[_ngcontent-%COMP%] {\r\n    cursor: pointer;\r\n}\r\nlabel[_ngcontent-%COMP%] {\r\n    color: #000;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9IUi9BdHRlbmRlbmNlL0F0dGVuZGVuY2UuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9FenNoaXBwLzEzLTAxLTIwMTgvc3VwZXJhZG1pbl9hbmd1bGFyL2Fzc2V0cy9hcHAvZGFzaGJvYXJkL0hSL0F0dGVuZGVuY2UvQXR0ZW5kZW5jZS5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
