/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './activeCustomer.module';
import * as i2 from './activeCustomers.component.ngfactory';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/common';
import * as i5 from '@angular/http';
import * as i6 from 'ngx-pagination';
import * as i7 from '@angular/router';
import * as i8 from 'ng2-img-cropper/src/imageCropperModule';
import * as i9 from '../../../shared/shared.module';
import * as i10 from './activeCustomers.component';
export const ActiveCustomeroduleNgFactory:i0.NgModuleFactory<i1.ActiveCustomerodule> = i0.ɵcmf(i1.ActiveCustomerodule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ActiveCustomerComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i3.ɵi,i3.ɵi,([] as any[])),i0.ɵmpd(4608,
          i4.NgLocalization,i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i5.BrowserXhr,
          i5.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i5.ResponseOptions,i5.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(5120,i5.XSRFStrategy,i5.ɵb,([] as any[])),i0.ɵmpd(4608,
          i5.XHRBackend,i5.XHRBackend,[i5.BrowserXhr,i5.ResponseOptions,i5.XSRFStrategy]),
          i0.ɵmpd(4608,i5.RequestOptions,i5.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i5.Http,i5.ɵc,[i5.XHRBackend,i5.RequestOptions]),i0.ɵmpd(4608,i6.PaginationService,
              i6.PaginationService,([] as any[])),i0.ɵmpd(512,i7.RouterModule,i7.RouterModule,
              [[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,i3.ɵba,i3.ɵba,([] as any[])),
          i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,([] as any[])),i0.ɵmpd(512,i4.CommonModule,
              i4.CommonModule,([] as any[])),i0.ɵmpd(512,i8.ImageCropperModule,i8.ImageCropperModule,
              ([] as any[])),i0.ɵmpd(512,i5.HttpModule,i5.HttpModule,([] as any[])),
          i0.ɵmpd(512,i6.NgxPaginationModule,i6.NgxPaginationModule,([] as any[])),
          i0.ɵmpd(512,i9.SharedModule,i9.SharedModule,([] as any[])),i0.ɵmpd(512,i1.ActiveCustomerodule,
              i1.ActiveCustomerodule,([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'',component:i10.ActiveCustomerComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9jdXN0b21lci9hY3RpdmVDdXN0b21lcnMvYWN0aXZlQ3VzdG9tZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0V6c2hpcHAvMTMtMDEtMjAxOC9zdXBlcmFkbWluX2FuZ3VsYXIvYXNzZXRzL2FwcC9kYXNoYm9hcmQvY3VzdG9tZXIvYWN0aXZlQ3VzdG9tZXJzL2FjdGl2ZUN1c3RvbWVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
