/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './createoffer.module';
import * as i2 from '../../../../../node_modules/angular2-busy/build/busy.component.ngfactory';
import * as i3 from '../../../../../node_modules/angular2-busy/build/busy-backdrop.component.ngfactory';
import * as i4 from './sessionalOffer.component.ngfactory';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/common';
import * as i7 from '@angular/http';
import * as i8 from 'ngx-pagination';
import * as i9 from 'angular2-busy/build/busy.service';
import * as i10 from 'angular2-busy/build/busy-config';
import * as i11 from 'angular2-busy/build/busy.module';
import * as i12 from '@angular/router';
import * as i13 from 'ng2-img-cropper/src/imageCropperModule';
import * as i14 from '../../../shared/shared.module';
import * as i15 from './sessionalOffer.component';
export const CreateOfferModuleNgFactory:i0.NgModuleFactory<i1.CreateOfferModule> = i0.ɵcmf(i1.CreateOfferModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.BusyComponentNgFactory,i3.BusyBackdropComponentNgFactory,i4.CreateOfferComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.ɵi,
          i5.ɵi,([] as any[])),i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i7.BrowserXhr,i7.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i7.ResponseOptions,i7.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,
              i7.XSRFStrategy,i7.ɵb,([] as any[])),i0.ɵmpd(4608,i7.XHRBackend,i7.XHRBackend,
              [i7.BrowserXhr,i7.ResponseOptions,i7.XSRFStrategy]),i0.ɵmpd(4608,i7.RequestOptions,
              i7.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i7.Http,i7.ɵc,[i7.XHRBackend,
              i7.RequestOptions]),i0.ɵmpd(4608,i8.PaginationService,i8.PaginationService,
              ([] as any[])),i0.ɵmpd(4608,i9.BusyService,i9.BusyService,[[2,i10.BusyConfig]]),
          i0.ɵmpd(5120,i0.Compiler,i11.createJitCompiler,([] as any[])),i0.ɵmpd(512,
              i12.RouterModule,i12.RouterModule,[[2,i12.ɵa],[2,i12.Router]]),i0.ɵmpd(512,
              i5.ɵba,i5.ɵba,([] as any[])),i0.ɵmpd(512,i5.FormsModule,i5.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,([] as any[])),
          i0.ɵmpd(512,i13.ImageCropperModule,i13.ImageCropperModule,([] as any[])),
          i0.ɵmpd(512,i7.HttpModule,i7.HttpModule,([] as any[])),i0.ɵmpd(512,i8.NgxPaginationModule,
              i8.NgxPaginationModule,([] as any[])),i0.ɵmpd(512,i14.SharedModule,i14.SharedModule,
              ([] as any[])),i0.ɵmpd(512,i11.BusyModule,i11.BusyModule,([] as any[])),
          i0.ɵmpd(512,i1.CreateOfferModule,i1.CreateOfferModule,([] as any[])),i0.ɵmpd(1024,
              i12.ROUTES,() => {
                return [[{path:'',component:i15.CreateOfferComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9PZmZlcnMvc2Vzc2lvbmFsT2ZmZXIvY3JlYXRlb2ZmZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0V6c2hpcHAvMTMtMDEtMjAxOC9zdXBlcmFkbWluX2FuZ3VsYXIvYXNzZXRzL2FwcC9kYXNoYm9hcmQvT2ZmZXJzL3Nlc3Npb25hbE9mZmVyL2NyZWF0ZW9mZmVyLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
