/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.backdrop[_ngcontent-%COMP%] {\r\n    display: block;\r\n    \r\n    position: fixed;\r\n    \r\n    z-index: 10;\r\n    \r\n    padding-top: 100px;\r\n    \r\n    left: 0;\r\n    top: 0;\r\n    width: 100%;\r\n    \r\n    height: 100%;\r\n    \r\n    overflow-y: scroll;\r\n    \r\n    background-color: #FFFFFF;\r\n    \r\n    background-color: rgba(0, 0, 0, 0.4);\r\n    \r\n }\r\n\r\n .modal[_ngcontent-%COMP%] {\r\n    display: block;\r\n    margin-top: 5%;\r\n    overflow-y: scroll;\r\n }\r\n\r\n .modal-content-dialog[_ngcontent-%COMP%] {\r\n    background-color: #fefefe;\r\n    margin: 100px 500px;\r\n    padding: 20px;\r\n    border: 1px solid #888;\r\n    width: 40%;\r\n    height: 200px;\r\n    font-size: 20px;\r\n }\r\n\r\n .fa[_ngcontent-%COMP%]:hover {\r\n     cursor: pointer;\r\n }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9jdXN0b21lci9wcmVtaXVtQ3VzdG9tZXIvY2xpZW50Q09EL2NsaWVudF9jb2QuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9FenNoaXBwLzEzLTAxLTIwMTgvc3VwZXJhZG1pbl9hbmd1bGFyL2Fzc2V0cy9hcHAvZGFzaGJvYXJkL2N1c3RvbWVyL3ByZW1pdW1DdXN0b21lci9jbGllbnRDT0QvY2xpZW50X2NvZC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
