export class FilterModel{
    constructor( public skip?,
    public limit?,
 public AdminID?,
 public CLEAR_ALL?,
 public Whether_Name_Filter?,
 public Name?,
 public Whether_PhoneNumber_Filter?,
 public PhoneNumber?,
 public Whether_New_Jobs_Filter?,
 public Whether_Ongoing_Jobs_Filter?,
 public Whether_Completed_Jobs_Filter?,
 public Whether_Expired_Jobs_Filter?,
 public Whether_Date_Filter?,
 public from_date?,
 public to_date?,
 public DriverID?,
 public Whether_Driver_Filter?,
 public Name_Query_Type?,
 public Whether_COD?,
 public Whether_Online?,
 public Payment_Captured?,
 public Payment_Not_Captured?,
 public sortOptions ?,
 public InstantType  ?,
 public fourHoursType  ?,
 public SameType  ?,
 public Whether_Pick_Zone_Filter  ?,
 public PickZoneArray  ?,
 public Whether_Drop_Zone_Filter   ?,
 public DropZoneArray   ?,


 ){}
 }

