export class OrderModel{
    constructor(public  CustomerID?,
                public pickAddress?,
                public dropAddress?,
                public pickLatitude?,
                public pickLongitude?,
                public dropLatitude?,
                public dropLongitude?,
                public itemName?,
                public itemDescription?,
                public order_datetime?,
                public orderType?,
                public bookingType?,
                public receiverName?,
                public receiverPhone?,
                public paymentType?,
                public deliverycharge?,
               public OrderData?: string[],
               public paymentId?,
               public Picture?,
               public itemImage?,
               public ImageID?,
public SessionID?,
public item_actual_cost?,
public OFFER_CODE_APPLIED ?,
public ReferenceOfferID ?,
public OfferID ?,
public OfferType ?
   ){}
}