/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './promotion.module';
import * as i2 from './promotion.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
import * as i5 from 'ngx-pagination';
import * as i6 from '@angular/router';
import * as i7 from './promotion.component';
export const PromotionModuleNgFactory:i0.NgModuleFactory<i1.PromotionModule> = i0.ɵcmf(i1.PromotionModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.PromotionComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(4608,i5.PaginationService,i5.PaginationService,
              ([] as any[])),i0.ɵmpd(4608,i4.FormBuilder,i4.FormBuilder,([] as any[])),
          i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i4.ɵba,
              i4.ɵba,([] as any[])),i0.ɵmpd(512,i4.FormsModule,i4.FormsModule,([] as any[])),
          i0.ɵmpd(512,i6.RouterModule,i6.RouterModule,[[2,i6.ɵa],[2,i6.Router]]),i0.ɵmpd(512,
              i5.NgxPaginationModule,i5.NgxPaginationModule,([] as any[])),i0.ɵmpd(512,
              i4.ReactiveFormsModule,i4.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,
              i1.PromotionModule,i1.PromotionModule,([] as any[])),i0.ɵmpd(1024,i6.ROUTES,
              () => {
                return [[{path:'',component:i7.PromotionComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9wcm9tb3Rpb24vcHJvbW90aW9uLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9FenNoaXBwLzEzLTAxLTIwMTgvc3VwZXJhZG1pbl9hbmd1bGFyL2Fzc2V0cy9hcHAvZGFzaGJvYXJkL3Byb21vdGlvbi9wcm9tb3Rpb24ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
