/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['chart[_ngcontent-%COMP%] {\r\n    display: block;\r\n    height: auto;\r\n\r\n\r\n  }\r\n  .ch[_ngcontent-%COMP%]{\r\n      width: 450px;\r\n      height: 150px\r\n  }\r\n  td[_ngcontent-%COMP%]{\r\n      border-top:none!important;\r\n  }\r\n  .active[_ngcontent-%COMP%]{\r\n    color: #705137 !important;\r\n\r\n    background-color: #ee9b0a !important;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9GX0FuYWx5dGljcy9GX0FuYWx5dGljcy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0V6c2hpcHAvMTMtMDEtMjAxOC9zdXBlcmFkbWluX2FuZ3VsYXIvYXNzZXRzL2FwcC9kYXNoYm9hcmQvRl9BbmFseXRpY3MvRl9BbmFseXRpY3MuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
