/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.activeForsorting[_ngcontent-%COMP%]{\r\n    color:lightcoral\r\n}\r\n.zone-heading[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    font-size: 23px;\r\n    font-family: Proxima-Nova-Regular;\r\n  }\r\n  \r\n  .instant[_ngcontent-%COMP%]{\r\n    color:#00BFFF\r\n }\r\n .FourHours[_ngcontent-%COMP%]{\r\n    color: #fb641b\r\n }\r\n .same[_ngcontent-%COMP%]{\r\n    color: #ee9b0a\r\n }\r\n .neworder[_ngcontent-%COMP%]{\r\n         color:#00bcd4\r\n     }\r\n.OrderCanceled[_ngcontent-%COMP%]\r\n{\r\n     color:#ff0000\r\n}	 \r\n.cancelorderbyuserorvendor[_ngcontent-%COMP%] {\r\n        color:#ff0000\r\n     }\r\n.cancelorderbyuserorvendornew[_ngcontent-%COMP%] {\r\n        color:#ff0000\r\n     }\r\n.Onthewaytodelivery[_ngcontent-%COMP%] {\r\n    color:#B87B0C\r\n}	 \r\n.reachedDeliverypoint[_ngcontent-%COMP%]{\r\n    color:#B87B0C\r\n}\r\n.OnthewaytoPickup[_ngcontent-%COMP%]\r\n{\r\n    color:#B87B0C\r\n}	 \r\n.completedorder[_ngcontent-%COMP%] {\r\n        color:#0E9C0E\r\n     }\r\n	 \r\n.processingorder[_ngcontent-%COMP%] {\r\n        color:#B87B0C\r\n     }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9vLkRlbGl2ZXJ5UmVwb3J0L28uRGVsaXZlcnlSZXBvcnQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9FenNoaXBwLzEzLTAxLTIwMTgvc3VwZXJhZG1pbl9hbmd1bGFyL2Fzc2V0cy9hcHAvZGFzaGJvYXJkL28uRGVsaXZlcnlSZXBvcnQvby5EZWxpdmVyeVJlcG9ydC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
