/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './smscampaign.module';
import * as i2 from './createcampaign/createcampaign.component.ngfactory';
import * as i3 from './viewallcampaign/viewallcampaign.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/http';
import * as i7 from 'ngx-pagination';
import * as i8 from '@angular/router';
import * as i9 from 'ng2-img-cropper/src/imageCropperModule';
import * as i10 from '../../shared/shared.module';
import * as i11 from './createcampaign/createcampaign.component';
import * as i12 from './viewallcampaign/viewallcampaign.component';
export const SmscampaignModuleNgFactory:i0.NgModuleFactory<i1.SmscampaignModule> = i0.ɵcmf(i1.SmscampaignModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.CreatecampaignComponentNgFactory,i3.ViewallcampaignComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i4.NgLocalization,
          i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i5.ɵi,i5.ɵi,([] as any[])),
          i0.ɵmpd(4608,i6.BrowserXhr,i6.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i6.ResponseOptions,
              i6.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i6.XSRFStrategy,i6.ɵb,
              ([] as any[])),i0.ɵmpd(4608,i6.XHRBackend,i6.XHRBackend,[i6.BrowserXhr,
              i6.ResponseOptions,i6.XSRFStrategy]),i0.ɵmpd(4608,i6.RequestOptions,
              i6.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i6.Http,i6.ɵc,[i6.XHRBackend,
              i6.RequestOptions]),i0.ɵmpd(4608,i7.PaginationService,i7.PaginationService,
              ([] as any[])),i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),
          i0.ɵmpd(512,i5.ɵba,i5.ɵba,([] as any[])),i0.ɵmpd(512,i5.FormsModule,i5.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i8.RouterModule,i8.RouterModule,[[2,i8.ɵa],
              [2,i8.Router]]),i0.ɵmpd(512,i9.ImageCropperModule,i9.ImageCropperModule,
              ([] as any[])),i0.ɵmpd(512,i6.HttpModule,i6.HttpModule,([] as any[])),
          i0.ɵmpd(512,i7.NgxPaginationModule,i7.NgxPaginationModule,([] as any[])),
          i0.ɵmpd(512,i10.SharedModule,i10.SharedModule,([] as any[])),i0.ɵmpd(512,
              i1.SmscampaignModule,i1.SmscampaignModule,([] as any[])),i0.ɵmpd(1024,
              i8.ROUTES,() => {
                return [[{path:'',redirectTo:'viewallcampaign'},{path:'createcampaign',
                    component:i11.CreatecampaignComponent},{path:'viewallcampaign',
                    component:i12.ViewallcampaignComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9zbXNjYW1wYWlnbi9zbXNjYW1wYWlnbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9zbXNjYW1wYWlnbi9zbXNjYW1wYWlnbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
