/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.isOdd[_ngcontent-%COMP%] {\r\n    background-color: #ddd;\r\n}\r\n\r\n.rotate[_ngcontent-%COMP%] {\r\n    \r\n    -webkit-transform: rotate(-90deg);\r\n    \r\n    -moz-transform: rotate(-90deg);\r\n    \r\n    -ms-transform: rotate(-90deg);\r\n    \r\n    -o-transform: rotate(-90deg);\r\n    \r\n    filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);\r\n}\r\n.activeForsorting[_ngcontent-%COMP%]{\r\n    color:lightcoral\r\n }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC92ZW5kb3JzQXBpUmVxdWVzdHMvdmVuZG9yc0FwaVJlcXVlc3RzLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC92ZW5kb3JzQXBpUmVxdWVzdHMvdmVuZG9yc0FwaVJlcXVlc3RzLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
