/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './cancelorders.module';
import * as i2 from '../../../../../node_modules/angular2-busy/build/busy.component.ngfactory';
import * as i3 from '../../../../../node_modules/angular2-busy/build/busy-backdrop.component.ngfactory';
import * as i4 from './cancelOrders.component.ngfactory';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/common';
import * as i7 from 'ngx-pagination';
import * as i8 from '@angular/http';
import * as i9 from 'angular2-busy/build/busy.service';
import * as i10 from 'angular2-busy/build/busy-config';
import * as i11 from 'angular2-busy/build/busy.module';
import * as i12 from '@angular/router';
import * as i13 from 'ng2-img-cropper/src/imageCropperModule';
import * as i14 from '../../../shared/shared.module';
import * as i15 from './cancelOrders.component';
export const CancelorderModuleNgFactory:i0.NgModuleFactory<i1.CancelorderModule> = i0.ɵcmf(i1.CancelorderModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.BusyComponentNgFactory,i3.BusyBackdropComponentNgFactory,i4.CancelOrderComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.ɵi,
          i5.ɵi,([] as any[])),i0.ɵmpd(4608,i6.NgLocalization,i6.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i7.PaginationService,i7.PaginationService,([] as any[])),
          i0.ɵmpd(4608,i8.BrowserXhr,i8.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i8.ResponseOptions,
              i8.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i8.XSRFStrategy,i8.ɵb,
              ([] as any[])),i0.ɵmpd(4608,i8.XHRBackend,i8.XHRBackend,[i8.BrowserXhr,
              i8.ResponseOptions,i8.XSRFStrategy]),i0.ɵmpd(4608,i8.RequestOptions,
              i8.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i8.Http,i8.ɵc,[i8.XHRBackend,
              i8.RequestOptions]),i0.ɵmpd(4608,i9.BusyService,i9.BusyService,[[2,i10.BusyConfig]]),
          i0.ɵmpd(5120,i0.Compiler,i11.createJitCompiler,([] as any[])),i0.ɵmpd(512,
              i12.RouterModule,i12.RouterModule,[[2,i12.ɵa],[2,i12.Router]]),i0.ɵmpd(512,
              i5.ɵba,i5.ɵba,([] as any[])),i0.ɵmpd(512,i5.FormsModule,i5.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,([] as any[])),
          i0.ɵmpd(512,i7.NgxPaginationModule,i7.NgxPaginationModule,([] as any[])),
          i0.ɵmpd(512,i13.ImageCropperModule,i13.ImageCropperModule,([] as any[])),
          i0.ɵmpd(512,i8.HttpModule,i8.HttpModule,([] as any[])),i0.ɵmpd(512,i14.SharedModule,
              i14.SharedModule,([] as any[])),i0.ɵmpd(512,i11.BusyModule,i11.BusyModule,
              ([] as any[])),i0.ɵmpd(512,i1.CancelorderModule,i1.CancelorderModule,
              ([] as any[])),i0.ɵmpd(1024,i12.ROUTES,() => {
            return [[{path:'',component:i15.CancelOrderComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9PcmRlcnMvY2FuY2VsT3JkZXJzL2NhbmNlbG9yZGVycy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9PcmRlcnMvY2FuY2VsT3JkZXJzL2NhbmNlbG9yZGVycy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
