/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.zone-heading[_ngcontent-%COMP%] {\r\n   text-align: center;\r\n   font-size: 23px;\r\n   font-family: Proxima-Nova-Regular;\r\n}\r\n.form-control[_ngcontent-%COMP%] {\r\n       width: 200px;\r\n   }\r\n.table-btn[_ngcontent-%COMP%] {\r\n       background-color: #e87906;\r\n       color: #fff;\r\n       box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.4), 0 3px 14px 0 rgba(0, 0, 0, 0.19);\r\n       padding: 5px;\r\n       margin-left: 100px;\r\n   }\r\n\r\n   .one_order[_ngcontent-%COMP%] {\r\n       width: 300px;\r\n       padding: 5px;\r\n       margin-left: 20px;\r\n   }\r\n\r\n   .border_table_hover[_ngcontent-%COMP%]:hover {\r\n       background-color: #12a6f1;\r\n       color: #fff;\r\n       cursor: pointer;\r\n   }\r\n\r\n   .border_table[_ngcontent-%COMP%] {\r\n       box-shadow: 0 0 4px rgba(0, 0, 0, 0.14), 0 4px 8px rgba(0, 0, 0, 0.28);\r\n   }\r\n\r\n   .td_style[_ngcontent-%COMP%] {\r\n       border-top: none;\r\n       width:50%;\r\n       padding: 5px;\r\n   }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9NYW51YWwtT3JkZXIvbWFudWFsX29yZGVyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9NYW51YWwtT3JkZXIvbWFudWFsX29yZGVyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
