/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.zone-heading[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    font-size: 23px;\r\n    font-family: Proxima-Nova-Regular;\r\n }\r\n\r\n .td-border-top[_ngcontent-%COMP%] {\r\n     border-top: none;\r\n }\r\n .active[_ngcontent-%COMP%]{\r\n     color: #f08080\r\n }'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovRXpzaGlwcC8xMy0wMS0yMDE4L3N1cGVyYWRtaW5fYW5ndWxhci9hc3NldHMvYXBwL2Rhc2hib2FyZC9jb2QtYmlrZXJzL2NvZC1iaWtlcnMuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9FenNoaXBwLzEzLTAxLTIwMTgvc3VwZXJhZG1pbl9hbmd1bGFyL2Fzc2V0cy9hcHAvZGFzaGJvYXJkL2NvZC1iaWtlcnMvY29kLWJpa2Vycy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
